version: "3.8"

x-common-variables: &common-variables
  - POSTGRES_DB=postgres
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres

networks:
  japp_stack:
services:
  db:
    image: postgres
    environment: *common-variables
    ports:
          - 5432:5432
    volumes:
      - "./data/postgres_volume:/var/lib/postgresql/data"
    networks:
      japp_stack:
        aliases:
          - db
          - postgres

  airflow:
    image: puckel/docker-airflow
    depends_on:
      - db
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - "./config/airflow/airflow-requirements.txt:/requirements.txt"
      - "./src/notebooks:/usr/local/airflow/notebooks"
      - "./src/pipelines:/usr/local/airflow/dags"
    networks:
      japp_stack:
        aliases:
          - airflow

  notebook:
    image: naveedn/japp_stack:notebook
    ports:
      - 8888:8888
      - 3000:3000
    depends_on:
      - db
    volumes:
      - "./src/notebooks:/home/jovyan/work"
      - "./src/pipelines:/home/jovyan/work/pipelines"
      - "./data:/data"
    environment: *common-variables
    networks:
      japp_stack:
        aliases:
          - notebook

  selenium:
    image: selenium/standalone-chrome
    ports:
        - 4444:4444
    networks:
      japp_stack:
        aliases:
          - selenium
